#!/bin/bash

branches=
branches="$branches $(git branch | awk '{print $NF}' | grep "^f\.")"
branches="$branches $(git branch | awk '{print $NF}' | grep "^t\.")"
branches="$branches $(git branch | awk '{print $NF}' | grep "^snp\.")"

cur_branch=$(./_script/_git_branch)
[ "$cur_branch" = "mix" ] \
    && git tag -f mixbkp \
    && git reset --hard root \
    && git mc --no-edit --commit internal \
    && git merge \
    --no-edit \
    --commit \
    --no-ff \
    $branches \
    && ./_script/update-doc \
    && git tag -f mixdoc

