#!/bin/sh

src_branch=mix
dst_branch=dev

cur_hash=$(git log -n1 --format="%H")
cur_branch=$(./_script/_git_branch)
if [ ".$cur_branch" = "." ]; then
    echo "not on a branch"
    exit 1
fi

dst_hash=$(git log -n1 --format="%H" $dst_branch)
src_tree_hash=$(git cat-file -p $src_branch | head -n1 | awk '{print $2}')

echo make new commit of $cur_branch with tree $src_tree_hash

new_commit_hash=$(echo "dev\n\nx-update-from: $src_branch $cur_hash" | git commit-tree $src_tree_hash -p $head_hash)
git checkout $dst_branch \
    && git merge --ff-only $new_commit_hash \
    && git commit --amend

git checkout $cur_branch
# to re-edit commit message
