#!/bin/bash

src_branch=mix
dst_branch=dev

cur_hash=$(git log -n1 --format="%H")
cur_branch=$(./_script/_git_branch)
if [ ".$cur_branch" = "." ]; then
    echo "not on a branch"
    exit 1
fi

src_tree_hash=$(git cat-file -p $src_branch | head -n1 | awk '{print $2}')

mes="dev\n\nx-update-from: $src_branch $cur_hash"

new_commit_hash=$(echo "$mes" | git commit-tree $src_tree_hash -p $dst_branch)
git checkout $dst_branch \
    && git merge --ff-only $new_commit_hash \
    && git commit --amend

git checkout $cur_branch
# to re-edit commit message
