#!/bin/sh

fn=doc/xpt/credit.txt

echo "Thanks to:\n" > $fn
git log --all --no-merges --format="%an" \
    | grep -v "drdr.\?xp\|xp\|zhang yanpo\|drmingdrmer\|no author" \
    | sort --ignore-case | uniq \
    >> $fn

cat _script/contributor.txt >>$fn
