#!/bin/sh


_script/credit-update \
    && _script/doc_merge.py \
    || exit 1

doc_sections="option snippet-function"
for sec in $doc_sections; do
    git rm -r doc/xpt/$sec || exit 1
done

vim -c "helptags ./doc" -c "qa!" \
    && git commit -a -m 'update doc'
